timeout: 5

/Gentoo Linux
    protocol: linux
    kernel_path: boot():/kernel-X.X.X-gentoo-dist-bin
    kernel_cmdline: root=UUID=yyyy-yyyy rw
    module_path: boot():/initramfs-X.X.X-gentoo-dist-bin.img
